### ISSUE TITLE
ha-cluster-vip for latest/edge

### ISSUE THREAD

**Issue by mcfly722** [canonical/pgbouncer-operator#212]
Hello,
I'm trying to build juju **PostgreSQL** cluster with 3 nodes and **PGBouncer+Data-integrator** available via single **VIP address**.

I found that **data-integrator** supports only ubuntu@22.04 versions:
```
data-integrator available releases are:
  channel "latest/stable": available bases are: ubuntu@22.04
  channel "latest/candidate": available bases are: ubuntu@22.04
  channel "latest/beta": available bases are: ubuntu@22.04
  channel "latest/edge": available bases are: ubuntu@22.04
```
This OS version (22.04) supports only 1/* versions of **PGBouncer**, but this versions does not supports **ha-cluster-vip/dns** parameters on configuration.

I would like to know, is there any way to build such cluster with VIP, or it is impossible and we have to wait ubuntu@22.04 support for pgbouncer latest/stable?

(here https://charmhub.io/pgbouncer/integrations?channel=1/edge integration with HACluster announced, but looks like does not support) 

## Steps to reproduce

```
juju integrate hacluster pgbouncer
```

## Expected behavior
```
integrated successfully
```

## Actual behavior
```
ERROR ambiguous relation: "hacluster pgbouncer" could refer to "hacluster:juju-info pgbouncer:juju-info"; "hacluster:peer-availability pgbouncer:juju-info"; "pgbouncer:juju-info hacluster:juju-info"
```

## Versions

Operating system:  **Ubuntu 22.04.4 LTS**

Juju CLI: **3.4.2-genericlinux-amd64**

```
ubuntu@jujunode1-tst:~$ juju status
Model            Controller          Cloud/Region        Version  SLA          Timestamp
postgresql-maas  lxd-remote-default  lxd-remote/default  3.4.2    unsupported  09:52:39Z

App              Version  Status   Scale  Charm            Channel        Rev  Exposed  Message
data-integrator           active       3  data-integrator  latest/stable   19  no
hacluster                 unknown      0  hacluster        2.4/stable     131  no
pgbouncer        1.21.0   active       3  pgbouncer        1/edge         142  yes
postgresql       14.11    active       3  postgresql       14/edge        393  yes

Unit                Workload  Agent  Machine  Public address  Ports     Message
data-integrator/0   active    idle   3        240.9.0.161
  pgbouncer/0       active    idle            240.9.0.161     6432/tcp
data-integrator/1*  active    idle   4        240.81.0.43
  pgbouncer/3*      active    idle            240.81.0.43     6432/tcp
data-integrator/2   active    idle   5        240.7.0.43
  pgbouncer/2       active    idle            240.7.0.43      6432/tcp
postgresql/0*       active    idle   0        240.81.0.166    5432/tcp
postgresql/1        active    idle   1        240.9.0.212     5432/tcp
postgresql/2        active    idle   2        240.7.0.203     5432/tcp  Primary

Machine  State    Address       Inst id        Base          AZ  Message
0        started  240.81.0.166  juju-f7af5d-0  ubuntu@22.04      Running
1        started  240.9.0.212   juju-f7af5d-1  ubuntu@22.04      Running
2        started  240.7.0.203   juju-f7af5d-2  ubuntu@22.04      Running
3        started  240.9.0.161   juju-f7af5d-3  ubuntu@22.04      Running
4        started  240.81.0.43   juju-f7af5d-4  ubuntu@22.04      Running
5        started  240.7.0.43    juju-f7af5d-5  ubuntu@22.04      Running
```

postgresql charm revision: 393
pgbouncer charm revision: 142

LXD: **5.21.1 **LTS****

**Comment by taurus-forever** [comment]
Hi @mcfly722 , thank you for trying our new charm and reporting your use case here!

We have documented the difference and tech details between legacy and modern pgbouncer charms: https://charmhub.io/pgbouncer/docs/e-legacy-charm?channel=1/edge and will use this bugreport as a reference to consider hacluster interface implementation on modern pgbouncer charm. As @dragomirp mentioned, the hacluster interface is currently not supported by modern charm at the moment.

**Comment by taurus-forever** [comment]
The interface: https://github.com/openstack/charm-interface-hacluster

**Comment by dragomirp** [comment]
`1/edge` (revs. 362, 363, 364, 365) should have the interface implemented.
